name: open_exchange_rates
description: A library for Open Exchange Rates API to make it easy to use and get data from the API right away.
version: 2.1.0
homepage: https://github.com/cychiang/open_exchange_rates
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  uri: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  mock_web_server: 5.0.0-nullsafety.1
  lints: ^2.0.0
  test: ^1.21.1
